Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -33,12 +33,18 @@ jobs:
         queries: './my-codeql/queries/iva-asignment.ql'
         output: '../results'
 
-    - name: Fail if any alerts were found
+    - name: Install jq
+      run: sudo apt-get install jq
+    - name: Display alerts
       run: |
-        if grep -q "\"results\"" ../results/csharp.sarif; then
-          echo "CodeQL found alerts"
-          exit 1
-        fi
+        jq '.runs[0].results[] | {ruleId: .ruleId, message: .message.text, location: .locations[0].physicalLocation.artifactLocation.uri}' ../results/csharp.sarif      
+  
+    #- name: Fail if any alerts were found
+    #  run: |
+    #    if grep -q "\"results\"" ../results/csharp.sarif; then
+    #      echo "CodeQL found alerts"
+    #      exit 1
+    #    fi
     
     - name: List results directory
       run: ls -la /home/runner/work/test-codeql/results/csharp.sarif
